name = "seaventurandonabiblia"
main = "dist/server/server.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "dist/client"

[[routes]]
pattern = "escoladeproposito.online/*"
zone_name = "escoladeproposito.online"
